apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs-server.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.volume.storageSize }}